### ISSUE TITLE
Links to libc in Documentation

### ISSUE THREAD

**Issue by mtib** [pornel/lodepng-rust#14]
links in the documentation to [libc](http://pornel.github.io/lodepng-rust/libc/index.html) end up in a 404 page.

This is not a major problem but is quite irritating when browsing or looking something up, as I am quite new to rust.

**Is there a reason not to have them?**

**Comment by pornel** [comment]
libc documentation is huge, and it's only a dependency of this library, not a part of it.

I've added some pages of libc to the docs.

**Comment by mtib** [comment]
ok. I didn't know.

I might try something, and create a Pr.
