### ISSUE TITLE
How do I convert CVec<Rgba<u8>> into a CVec<u8>?

### ISSUE THREAD

**Issue by quadrupleslap** [pornel/lodepng-rust#21]
The docs mention using `mem::transmute`, but I can't figure it out. 😞 

Additionally, the `README` says:

> and the buffer has .as_bytes() method if you need a plain [u8]

but nothing like that method seems to exist on anything except the `RGBA` type itself.

Alternatively is there some way I can get a `CVec<u8>` out of `lodepng::decode32`?

**Comment by pornel** [comment]
I've updated the readme

**Comment by quadrupleslap** [comment]
Thanks! But to clarify - how do I get an **owned** byte vector out of a `CVec<RGBA<u8>>`?

**Comment by pornel** [comment]
Call `to_owned()` on the slice. There's no way to do it without copying, because they use potentially incompatible memory allocators.

**Comment by quadrupleslap** [comment]
Okay, that's a.bit sad. Anyway, I ended up just wrapping the
`CVec<RGBA<u8>>`. :) if you don't mind sanity-checking it the code's at
`endogeny/png-framing/src/lib.rs`.
