### ISSUE TITLE
Document that the source uses unstable features, and therefore requires a Rust nightly install

### ISSUE THREAD

**Issue by StrayLightning** [pornel/lodepng-rust#23]
The package uses unstable features, and therefore requires one of the Nightly builds of Rust, which seems worth documenting.  For example, building with Rust 1.20.0:

 error: use of unstable library feature 'ord_max_min' (see issue #25663)
     --> src/rustimpl.rs:2158:42
      |
 2158 |         let len = (data.len() - datapos).min(65535);
      |                                          ^^^

**Comment by pornel** [comment]
It's a bit cutting edge, but `Ord::min` is now [stable in 1.21](https://doc.rust-lang.org/std/cmp/trait.Ord.html#method.min). If you're using `rustup`, `rustup update` will fix it.

**Comment by pornel** [comment]
Noted in e12fd88f3cecf78e7e802b3dafe7f7140547363e
